Added support for ZFS file system.
theqvd/theqvd pull request #55
Opened 2017-02-14 18:48 UTC by CrisBSD

Hi to all qvd team, I maked the backend to support the zfs file system.

Best regards,

2017-02-16 07:59 UTC, salva requested changes

2017-02-16 07:59 UTC, salva commented on ext/QVD-HKD/Makefile.PL
> +	'Filesys::ZFS' => '1.5'
It seems that Filesys::ZFS is just a thin wrapper around `zpool` and `zfs` commands and you are not actually using more than its `_run` method. So, I think we can remove its usage completely from the module.

2017-02-23 13:33 UTC, salva commented
@CrisBSD: I have created a new branch [zfs](/theqvd/theqvd/tree/zfs) with your code and some additional improvements. Could you check it?

I have changed the way the backend is configured. Now you only need to set `path.storage.basefs` and `path.storage.overlayfs` pointing to two paths corresponding to two ZFS datasets from a common pool. For instance:

    zpool create qvd /dev/sdb
    zfs create qvd/basefs
    zfs create qvd/overlayfs
    qa config set path.storage.basefs = /qvd/basefs
    qa config set path.storage.overlayfs = /qvd/overlayfs

2017-02-23 13:33 UTC, salva approved these changes

2017-03-07 16:19 UTC, CrisBSD commented
@salva: I saw the code and think that is more clean and elegant, thanks for accept it. It would be great to integrate it into the master branch, and thank you for the learning, I hope send more contributions with this quality.

Best Regards,

2017-03-08 07:58 UTC, salva commented
@CrisBSD, have you actually tried the version on the [zfs branch](https://github.com/theqvd/theqvd/tree/zfs)?

2022-02-05 14:39 UTC, closed without merging